baseURL = 'https://wyattclarke.github.io/place-for-family/'
languageCode = 'en-us'
title = 'Creating Place for Family'
theme = 'ananke'

Paginate = 30

[[menu.main]]
name = "Philosophy"
url = "/philosophy"
weight = 1

[[menu.main]]
name = "Schemes"
url = "/schemes"
weight = 2

[[menu.main]]
name = "Real Estate"
url = "/real_estate"
weight = 3

[[menu.main]]
name = "CPS"
url = "/CPS"
weight = 4

[[menu.main]]
name = "Book Reflections"
url = "/books"
weight = 5