baseURL = 'https://wyattclarke.github.io/place-for-family/'
languageCode = 'en-us'
title = 'Creating Place for Family'
theme = 'ananke'

Paginate = 30

[[menu.main]]
name = "Thoughts"
url = "/thoughts"
weight = 1

[[menu.main]]
name = "Schemes"
url = "/schemes"
weight = 2

[[menu.main]]
name = "CPS"
url = "/CPS"
weight = 3

[[menu.main]]
name = "Books"
url = "/books"
weight = 4